### ISSUE TITLE
Prohibit invalid delete message creations

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#362] opened 2018-09-19 09:22 UTC
I can create a delete message from `Lifeline2` to `Lifeline1` between the existing sync message and existing delete messagein the following scenario...
![image](https://user-images.githubusercontent.com/588090/45744130-07b21a00-bbfe-11e8-9a89-a8cf461cefaa.png)
... leading to ...
![image](https://user-images.githubusercontent.com/588090/45744179-2fa17d80-bbfe-11e8-9c73-68bb35a771e7.png)

**Comment by cdamus** [comment] 2018-09-20 19:27
Sorry, but I actually have a fix for this in the context of my work on self-messages (#59), so I think I'd better re-assign it to myself.  Note that a part of the problem is that the logical model doesn't yet have a representation of destruction occurrence specifications!

**Comment by planger** [comment] 2018-09-21 07:01
@cdamus Perfect, thanks!

**Closed** 2018-09-21 15:39 UTC
Labels: bug, prio_medium
